/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java2jni_FinalNative */

#ifndef _Included_java2jni_FinalNative
#define _Included_java2jni_FinalNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java2jni_FinalNative
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java2jni_FinalNative_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
