/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class secjava2jni_SecondFinalNative */

#ifndef _Included_secjava2jni_SecondFinalNative
#define _Included_secjava2jni_SecondFinalNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     secjava2jni_SecondFinalNative
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_secjava2jni_SecondFinalNative_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
